name: Javadoc Generation
on:
  push:
    branches:
      - 'master'
      - 'testing-*'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2

    - name: Set up the JDK environment
      uses: actions/setup-java@v2
      with:
        java-version: 16
        distribution: 'adopt'
        cache: gradle

    - name: Check Gradle version
      run: ./gradlew --version

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

    - name: Generate documentation with Javadoc
      run: javadoc -d javadoc-output $(find . -name "*.java") -Xdoclint:none --ignore-source-errors

    - name: Upload the Javadoc output
      uses: actions/upload-artifact@v2
      with:
        name: Javadoc-output
        path: ./javadoc-output/

    - name: Commit and push new Javadoc folder
      run: |
        # Set up Git and environment variables
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        shopt -s dotglob
        export BRANCH_NAME=$(echo $GITHUB_REF | sed -e "s/refs\/heads\///")

        # Move Javadocs and build reports
        mv javadoc-output/ ..
        mkdir ../team-reports/
        mv ./TeamCode/build/reports/*  ../team-reports/
        mkdir ../sdk-reports/
        mv ./FtcRobotController/build/reports/* ../sdk-reports/

        # Checkout gh-pages branch
        git remote set-branches origin '*'
        git fetch -v
        git checkout gh-pages

        # Copy Javadocs to gh-pages
        rm -rf ./javadocs/${BRANCH_NAME}/ || true
        mkdir -p ./javadocs/${BRANCH_NAME}/
        mv ../javadoc-output/* ./javadocs/${BRANCH_NAME}/

        # Copy build reports to gh-pages
        rm -rf ./reports/${BRANCH_NAME}/ || true
        mkdir -p ./reports/${BRANCH_NAME}/team-reports/
        mkdir -p ./reports/${BRANCH_NAME}/sdk-reports/
        mv ../team-reports/* ./reports/${BRANCH_NAME}/team-reports/
        mv ../sdk-reports/* ./reports/${BRANCH_NAME}/sdk-reports/
        mv ./reports/${BRANCH_NAME}/team-reports/lint-results-debug.html ./reports/${BRANCH_NAME}/team-reports/index.html
        mv ./reports/${BRANCH_NAME}/sdk-reports/lint-results-debug.html ./reports/${BRANCH_NAME}/sdk-reports/index.html

        # Commit and push changes
        git add .
        git commit -a -m "Javadoc documentation update ($GITHUB_RUN_NUMBER)
        Information:
            Repository: $GITHUB_REPOSITORY
            Branch: $GITHUB_REF
            Commit: $GITHUB_SHA
            Who triggered action: $GITHUB_ACTOR"
        git push
